### ISSUE TITLE
Make Halik open source

### ISSUE THREAD

**Issue by Zasch** [pbadenski/halik#10]
Sadly the development of Halik has stopped (https://twitter.com/halik_io/status/773838797880619010), but the source still is not available.
Please make the source code accessible, so others can use it.

**Comment by Fabian42** [comment]
You could try sending a mail: Pawel.Badenski@gmail.com

**Comment by pbadenski** [comment]
It's been long nearly 3 years. Other priorities seems to have always been winning but I have finally uploaded the source code...

**Comment by Fabian42** [comment]
Wait… Was I totally blind when I looked at this repository yesterday or can you retroactively change the change date of folders? Everything there says that it was last changed 3 years ago, but I could have sworn that it wasn't there a few hours ago…
