### ISSUE TITLE
Unable to add variables to watches

### ISSUE THREAD

**Issue by aNNiMON** [pbadenski/halik#5]
In the following code:

``` java
package halik.test;

import java.util.Arrays;

public class Main {

    public static void main(String[] args) {
        int[] array = {4, 1, 6, 3, 0, 4};
        for (int i = 0; i < array.length - 1; i++) {
            int minKey = i, min = array[i];
            for (int j = i + 1; j < array.length; j++) {
                if (array[j] < min) {
                    min = array[j];
                    minKey = j;
                }
            }
            int temp = array[i];
            array[i] = min;
            array[minKey] = temp;
        }
        System.out.println(Arrays.toString(array));
    }
}
```

I can't add `minKey` and `j` to watches and `temp` changes like `j`. Here's demo

![halik_issue](https://cloud.githubusercontent.com/assets/1321838/15992831/cd0da574-30de-11e6-8be8-400caa07a2c2.gif)

I use Intellij Idea with the Halik plugin 0.0.5.4.
Java version 1.8.0_91
Javac version 1.8.0_74
Language level 1.6 (same issue on 1.8)

**Comment by pbadenski** [comment]
Fixed in [0.0.5.5](https://plugins.jetbrains.com/update/index?pr=idea&updateId=26488)
