### ISSUE TITLE
Can't find core.clj in classpath for clojure

### ISSUE THREAD

**Issue by achikin** [pbadenski/halik#9]
Here is a summary screenshot of my code structure, target setup and main function contents set up according to your documentation.
As you can see - java couldn't find my main file. How can fix this?
<img width="1280" alt="screen shot 2016-09-05 at 03 33 28" src="https://cloud.githubusercontent.com/assets/611419/18234862/d602da3c-7319-11e6-92d3-af7ad5c3d427.png">

**Comment by pbadenski** [comment]
You need to mark "src" in your project directory as "Sources root".
